### ISSUE TITLE
Drop target delegate method not call

### ISSUE THREAD

**Issue by iPhoenix444** [frenetisch-applaudierend/ios-drag-and-drop#13]
I have try with swift 3.0 and my code is below

import UIKit
import DNDDragAndDrop

class ViewController: UIViewController , DNDDragSourceDelegate,DNDDropTargetDelegate  {

    @IBOutlet weak var dragSourceView: UIImageView!
    @IBOutlet var pangest: UIPanGestureRecognizer!
    @IBOutlet var dropTargetViews: [UIImageView]!
    var DragAndDropController = DNDDragAndDropController()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        DragAndDropController.registerDragSource(self.dragSourceView, with: self)

        for IM in self.dropTargetViews {
            IM.layer.borderColor = UIColor.blue.cgColor
            IM.layer.borderWidth = 2.0
            IM.isUserInteractionEnabled = true
            DragAndDropController.registerDropTarget(IM, with: self)
        }

    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    // Drag source delegate
    
    
    func draggingView(for operation: DNDDragOperation) -> UIView? {
    
        let imgview : UIImageView = UIImageView()
        imgview.frame = dragSourceView.frame
        imgview.image = dragSourceView.image
        imgview.isUserInteractionEnabled = true
        self.view.addSubview(imgview)
        return imgview
        
    }
    
    func dragOperationWillCancel(_ operation: DNDDragOperation) {
        
        print("cancel")
        
    }

    //Drop target delegate
    
    func dragOperation(_ operation: DNDDragOperation, didDropInDropTarget target: UIView) {
        
        print(target.tag)
        
    }
    
    func dragOperation(_ operation: DNDDragOperation, didEnterDropTarget target: UIView) {
        
        print(target.tag)
    }
    
    func dragOperation(_ operation: DNDDragOperation, didLeaveDropTarget target: UIView) {
        
        print(target.tag)
    }
    
}

when i drag image and drop on target always dragOperationWillCancel method call.
please help me to solve this issue
Thanks in advance

**Comment by frenetisch-applaudierend** [comment]
Hi!

From what I can tell your code looks ok. One thing that comes to mind is that maybe the drop target views are behind another (likely invisible) view. In this case the drag and drop operation would not be able to find the drop targets (they need to be on top).
