### ISSUE TITLE
Is there any way to support multi-touch drag?

### ISSUE THREAD

**Issue by ERbittuu** [frenetisch-applaudierend/ios-drag-and-drop#19]
I want to create an app that uses multi-touch and drag multiple tiles from one place to another place in one parent view.

Is it possible with this library?

**Comment by ERbittuu** [comment]
Yes, but I am working is an application which is supported minimum ios-9.3, so I can't use ios-11 built-in drag and drop API.

Please let me know is it possible with this library with some minor code changes?

Thanks.

**Comment by frenetisch-applaudierend** [comment]
Quite likely this is not easily implemented, given the architecture I chose (having a gesture recognizer per drag source). You could try to allow the gesture recognizers to recognize concurrently (via their delegates), but this might lead to other problems.

**Comment by ERbittuu** [comment]
Ok, I will try that. 

Thanks.
