### ISSUE TITLE
An option to prevent removing of the dragging view

### ISSUE THREAD

**Issue by mkoosej** [frenetisch-applaudierend/ios-drag-and-drop#6]

**Comment by frenetisch-applaudierend** [comment]
You can reuse the dragging view if you want.

In your -dragOperation:didDropInTarget: you must use one of the -removeDraggingView methods to remove the dragging view from the view hierarchy. Afterwards you may add the dragging view to your own hierarchy. 

Does this help you?

**Comment by mkoosej** [comment]
Yeah I ended up cloning the view. thx
